development: &default
  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  # Credentials for REST APIs
  client_id: AVfskeu3BkDR46tsnKll7A4PzvFnEwqMOzzyQ5GcS3LRZtx17uhQc3u3P-3M4Ia3dvUsD_usUfQRUR_k
  client_secret: EHNguFiUKzwIeBRY9iap03QmT-YO4DikLIpHGwR3RXe-0RcAEfXT9a_fZKMi56bQfuXN4N-fh3p5scUD


  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  mode: live
